### ISSUE TITLE
No effect when working with Proxy models

### ISSUE THREAD

**Issue by dix75** [Daguerreo/QMLTreeView#12]
Hi
I added a proxy model to filter the data, but there is actually no filtering.

Do I need to force update the data by sending a signal to the view?

**Comment by Daguerreo** [comment]
I didn't try proxy models. Try updating the data as you suggested. If you want to point out an example we can take a look at that.

**Comment by Daguerreo** [comment]
The errors are because you're commented the depth function in your model and then you're trying to call it.

What do you mean with automatic update? In which case the view should be updated?

**Comment by Daguerreo** [comment]
I tried your fork, but has several compile errors and crash (depth() is commented, Layouts version is 1.15, not 2.15, need to  clear the console.log).

Please push a working version so I could take a look better.

**Comment by dix75** [comment]
I am using version qt 6.5
The code works fine, but the program crashes if the 'a' character is entered.
There is no problem with other characters and text.

**Comment by Daguerreo** [comment]
Do the models works properly with a QTreeView widget?

**Comment by dix75** [comment]
Yes, of course.

**Comment by Daguerreo** [comment]
> Yes, of course.

I tried to debug it, it's kinda weird. It's happens with 'a' and 'i' in the sample, I have not clue in this moment, I've marked this as bug

**Comment by Daguerreo** [comment]
@dix75 if you  solved this in any way, could you point out the solution please?
