### ISSUE TITLE
how to clear the treeModel

### ISSUE THREAD

**Issue by hussainkadori** [Daguerreo/QMLTreeView#8]
Hi,
How to clear the model of the tree?
I called the clear() function but it didn't work.

**Comment by Daguerreo** [comment]
`clear()` actually clear the model, but the QML part of the visual remotion is not implemented yet. I suggest you as a workaround to put the view in a `Loader` and reload the component when the model is cleared.

PR are welcome if you want to implement it though.

**Comment by Daguerreo** [comment]
@hussainkadori I'm working on it. Clear already work and addition it's mostly, you can find it in the feature branch or wait for the release

**Comment by hussainkadori** [comment]
> @hussainkadori I'm working on it. Clear already work and addition it's mostly, you can find it in the feature branch or wait for the release
Thanks, it works 👍
